version: '3.10.12'
services:
  python:
    image: parunng/car_price_prediction:a3
    platform: linux/x86_64
    build:
      context: .
      dockerfile: .Dockerfile
    volumes:
      - ./code:/root/code
    ports:
      - 9001:80
    environment:
      - HOST=0.0.0.0
      - PORT=80